export const Admin = {
  ADMIN_LOGIN_REQUEST: "ADMIN_LOGIN_REQUEST",
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAILURE: "ADMIN_LOGIN_FAILURE",
  ADMIN_LOGIN_CLEAR: "ADMIN_LOGIN_CLEAR",

  CUSTOMER_LOGIN_REQUEST: "CUSTOMER_LOGIN_REQUEST",
  CUSTOMER_LOGIN_SUCCESS: "CUSTOMER_LOGIN_SUCCESS",
  CUSTOMER_LOGIN_FAILURE: "CUSTOMER_LOGIN_FAILURE",

  CUSTOMER_LIST_REQUEST: "CUSTOMER_LIST_REQUEST",
  CUSTOMER_LIST_SUCCESS: "CUSTOMER_LIST_SUCCESS",
  CUSTOMER_LIST_FAILURE: "CUSTOMER_LIST_FAILURE",

  SINGLE_CUSTOMER_REQUEST: "SINGLE_CUSTOMER_REQUEST",
  SINGLE_CUSTOMER_SUCCESS: "SINGLE_CUSTOMER_SUCCESS",
  SINGLE_CUSTOMER_FAILURE: "SINGLE_CUSTOMER_FAILURE",

  TRANSACTION_REQUEST: "TRANSACTION_REQUEST",
  TRANSACTION_SUCCESS: "TRANSACTION_SUCCESS",
  TRANSACTION_FAILURE: "TRANSACTION_FAILURE",

  DELETE_CUSTOMER_REQUEST: "DELETE_CUSTOMER_REQUEST",
  DELETE_CUSTOMER_SUCCESS: "DELETE_CUSTOMER_SUCCESS",
  DELETE_CUSTOMER_FAILURE: "DELETE_CUSTOMER_FAILURE",

  ADMIN_LOGOUT: "ADMIN_LOGOUT",
  CUSTOMER_LOGOUT: "CUSTOMER_LOGOUT",

  CREATE_TRANSACTION_REQUEST: "CREATE_TRANSACTION_REQUEST",
  CREATE_TRANSACTION_SUCCESS: "CREATE_TRANSACTION_SUCCESS",
  CREATE_TRANSACTION_FAILURE: "CREATE_TRANSACTION_FAILURE",
  CLEAR_TRANSACTION_DATA: "CLEAR_TRANSACTION_DATA",

  ALL_TRANSACTION_REQUEST: "ALL_TRANSACTION_REQUEST",
  ALL_TRANSACTION_SUCCESS: "ALL_TRANSACTION_SUCCESS",
  ALL_TRANSACTION_FAILURE: "ALL_TRANSACTION_FAILURE",

  UPDATE_USER_INFO_REQUEST: "UPDATE_USER_INFO_REQUEST",
  UPDATE_USER_INFO_SUCCESS: "UPDATE_USER_INFO_SUCCESS",
  UPDATE_USER_INFO_FAILURE: "UPDATE_USER_INFO_FAILURE",

  DELETE_SINGLE_USER: "DELETE_SINGLE_USER",

  GET_USER_TRANSACTION_REQUEST: "GET_USER_TRANSACTION_REQUEST",
  GET_USER_TRANSACTION_SUCCESS: "GET_USER_TRANSACTION_SUCCESS",
  GET_USER_TRANSACTION_FAILURE: "GET_USER_TRANSACTION_FAILURE",

  CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE: "CREATE_USER_FAILURE",
  CLEAR_CREATE_USER_RESPONSE: "CLEAR_CREATE_USER_RESPONSE",

  CLEAR_ERR: "CLEAR_ERR",
  SET_TOKEN: "SET_TOKEN",
  SET_USER_TOKEN: "SET_USER_TOKEN",
};
